path_classifiers:
  test:
    - "source/include/accio/*.h"
    - "source/include/accio/details/*.h"
    - "source/include/accio/testing/*.h"
    - "source/tests/*.cc"
  docs:
    - Readme.md
    - LICENSE
extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - g++-5
    configure:    # Customizable step used only by C/C++ extraction.
      command:
        - mkdir -p build && cd build
        - cmake -DCMAKE_CXX_FLAGS="-Werror -Wextra" -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=$PWD/.. ..
    index:    # Customizable step used by all languages.
      build_command:
        - make install
