
language: cpp
dist: trusty
sudo: required

os: linux
compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3 # default, osx 10.12
    - os: osx
      compiler: clang
      osx_image: xcode9.3 # osx 10.13

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.4

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "g++"  ]];
    then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5.4 90;
    fi
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=$PWD/.. ..
  - make install
  - ctest --output-on-failure

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
