
language: cpp
dist: trusty
sudo: required

os: linux
compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3 # default, osx 10.12
    - os: osx
      compiler: clang
      osx_image: xcode9.3 # osx 10.13

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "g++"  ]];
    then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90;
    fi
    if [[ "${TRAVIS_EVENT_TYPE}" == "cron"]];
    then ./.travis-ci.d/coverity_scan.sh;
    else
    then ./.travis-ci.d/compile_and_test.sh;
    fi

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
